/* Exemplo de Programa na linguagem L */

int b := -2;

main
{
  if ('c' > 'd') then {
      if (n[0] > n[2]) then max:=3; else max:=n[2];
    } else if (2 > n[2]) then max:=n[1]; else max:=n[2];

  for (i:=0; i<2; i:=i+1) {
    write("Digite um numero: ");
    readln(n[i]);
  }
  if ((2 > 3) and (3 < 4)) then {
    if (n[0] > n[2]) then max:=3; else max:=n[2];
  } else if (2 > n[2]) then max:=n[1]; else max:=n[2];
  writeln("O maior numero e' ",max);
}